extends Node

# Global campaign country database. National identity is represented through
# country metadata, uniforms, equipment and language options; gameplay spaces are fictionalized.
const COUNTRIES := [
    ["Türkiye","ASYA/AVRUPA","Ankara",1],["Arnavutluk","AVRUPA","Tiran",2],["Andorra","AVRUPA","Andorra la Vella",2],["Avusturya","AVRUPA","Viyana",2],["Belarus","AVRUPA","Minsk",2],["Belçika","AVRUPA","Brüksel",2],["Bosna-Hersek","AVRUPA","Saraybosna",2],["Birleşik Krallık","AVRUPA","Londra",4],["Bulgaristan","AVRUPA","Sofya",2],["Çekya","AVRUPA","Prag",3],["Danimarka","AVRUPA","Kopenhag",3],["Estonya","AVRUPA","Tallinn",3],["Finlandiya","AVRUPA","Helsinki",3],["Fransa","AVRUPA","Paris",3],["Hırvatistan","AVRUPA","Zagreb",3],["Hollanda","AVRUPA","Amsterdam",3],["İrlanda","AVRUPA","Dublin",3],["İspanya","AVRUPA","Madrid",3],["İsveç","AVRUPA","Stockholm",3],["İsviçre","AVRUPA","Bern",3],["İtalya","AVRUPA","Roma",3],["İzlanda","AVRUPA","Reykjavik",3],["Karadağ","AVRUPA","Podgorica",2],["Kıbrıs","AVRUPA","Lefkoşa",2],["Kuzey Makedonya","AVRUPA","Üsküp",2],["Letonya","AVRUPA","Riga",3],["Lihtenştayn","AVRUPA","Vaduz",2],["Litvanya","AVRUPA","Vilnius",3],["Lüksemburg","AVRUPA","Lüksemburg",2],["Macaristan","AVRUPA","Budapeşte",3],["Malta","AVRUPA","Valletta",2],["Moldova","AVRUPA","Kişinev",2],["Monako","AVRUPA","Monako",2],["Norveç","AVRUPA","Oslo",3],["Polonya","AVRUPA","Varşova",3],["Portekiz","AVRUPA","Lizbon",3],["Romanya","AVRUPA","Bükreş",3],["Rusya","AVRUPA","Moskova",5],["San Marino","AVRUPA","San Marino",2],["Sırbistan","AVRUPA","Belgrad",3],["Slovakya","AVRUPA","Bratislava",3],["Slovenya","AVRUPA","Ljubljana",3],["Ukrayna","AVRUPA","Kyiv",5],["Vatikan","AVRUPA","Vatikan",1],["Yunanistan","AVRUPA","Atina",2],
    ["Afganistan","ASYA","Kabil",5],["Azerbaycan","ASYA","Bakü",3],["Bahreyn","ASYA","Manama",3],["Bangladeş","ASYA","Dakka",3],["Bhutan","ASYA","Thimphu",2],["Brunei","ASYA","Bandar Seri Begawan",2],["Birleşik Arap Emirlikleri","ASYA","Abu Dabi",4],["Çin","ASYA","Pekin",5],["Endonezya","ASYA","Cakarta",4],["Ermenistan","ASYA","Erivan",3],["Filipinler","ASYA","Manila",4],["Gürcistan","ASYA","Tiflis",3],["Güney Kore","ASYA","Seul",4],["Hindistan","ASYA","Yeni Delhi",4],["Irak","ASYA","Bağdat",4],["İran","ASYA","Tahran",4],["İsrail","ASYA","Kudüs",4],["Japonya","ASYA","Tokyo",5],["Kamboçya","ASYA","Phnom Penh",3],["Katar","ASYA","Doha",4],["Kazakistan","ASYA","Astana",4],["Kırgızistan","ASYA","Bişkek",3],["Kuveyt","ASYA","Kuveyt",4],["Laos","ASYA","Vientiane",2],["Lübnan","ASYA","Beyrut",3],["Malezya","ASYA","Kuala Lumpur",4],["Maldivler","ASYA","Malé",2],["Moğolistan","ASYA","Ulan Batur",3],["Myanmar","ASYA","Naypyidaw",3],["Nepal","ASYA","Katmandu",3],["Özbekistan","ASYA","Taşkent",3],["Pakistan","ASYA","İslamabad",4],["Singapur","ASYA","Singapur",4],["Sri Lanka","ASYA","Sri Jayawardenepura Kotte",3],["Suudi Arabistan","ASYA","Riyad",4],["Tacikistan","ASYA","Duşanbe",3],["Tayland","ASYA","Bangkok",4],["Türkmenistan","ASYA","Aşkabat",3],["Umman","ASYA","Maskat",3],["Ürdün","ASYA","Amman",3],["Vietnam","ASYA","Hanoi",4],["Yemen","ASYA","Sana",5],["Kuzey Kore","ASYA","Pyongyang",5],["Doğu Timor","ASYA","Dili",2],["Filistin","ASYA","Ramallah",4],
    ["Angola","AFRİKA","Luanda",4],["Benin","AFRİKA","Porto-Novo",2],["Botsvana","AFRİKA","Gaborone",2],["Burkina Faso","AFRİKA","Ouagadougou",3],["Burundi","AFRİKA","Gitega",3],["Cabo Verde","AFRİKA","Praia",2],["Cezayir","AFRİKA","Cezayir",4],["Cibuti","AFRİKA","Cibuti",3],["Çad","AFRİKA","N'Djamena",4],["Ekvator Ginesi","AFRİKA","Malabo",3],["Eritre","AFRİKA","Asmara",4],["Esvatini","AFRİKA","Mbabane",2],["Etiyopya","AFRİKA","Addis Ababa",4],["Fas","AFRİKA","Rabat",2],["Fildişi Sahili","AFRİKA","Yamoussoukro",3],["Gabon","AFRİKA","Libreville",3],["Gambiya","AFRİKA","Banjul",2],["Gana","AFRİKA","Accra",3],["Gine","AFRİKA","Conakry",3],["Gine-Bissau","AFRİKA","Bissau",2],["Güney Afrika","AFRİKA","Pretoria",4],["Güney Sudan","AFRİKA","Juba",4],["Kamerun","AFRİKA","Yaoundé",4],["Kenya","AFRİKA","Nairobi",3],["Komorlar","AFRİKA","Moroni",2],["Kongo Cumhuriyeti","AFRİKA","Brazzaville",3],["Kongo Demokratik Cumhuriyeti","AFRİKA","Kinşasa",4],["Lesotho","AFRİKA","Maseru",2],["Liberya","AFRİKA","Monrovia",3],["Libya","AFRİKA","Trablus",4],["Madagaskar","AFRİKA","Antananarivo",3],["Malavi","AFRİKA","Lilongwe",2],["Mali","AFRİKA","Bamako",4],["Mısır","AFRİKA","Kahire",3],["Mauritius","AFRİKA","Port Louis",2],["Moritanya","AFRİKA","Nuakşot",3],["Mozambik","AFRİKA","Maputo",3],["Namibya","AFRİKA","Windhoek",3],["Nijer","AFRİKA","Niamey",4],["Nijerya","AFRİKA","Abuja",4],["Orta Afrika Cumhuriyeti","AFRİKA","Bangui",4],["Ruanda","AFRİKA","Kigali",3],["Sao Tome ve Principe","AFRİKA","São Tomé",2],["Senegal","AFRİKA","Dakar",3],["Seyşeller","AFRİKA","Victoria",2],["Sierra Leone","AFRİKA","Freetown",3],["Somali","AFRİKA","Mogadişu",5],["Sudan","AFRİKA","Hartum",5],["Tanzanya","AFRİKA","Dodoma",3],["Togo","AFRİKA","Lomé",2],["Tunus","AFRİKA","Tunus",3],["Uganda","AFRİKA","Kampala",3],["Zambiya","AFRİKA","Lusaka",3],["Zimbabve","AFRİKA","Harare",3],["Ekvator Ginesi","AFRİKA","Malabo",3],["Batı Sahra","AFRİKA","El Aaiún",3],
    ["Antigua ve Barbuda","KUZEY AMERİKA","Saint John's",1],["ABD","KUZEY AMERİKA","Washington",4],["Bahama","KUZEY AMERİKA","Nassau",2],["Barbados","KUZEY AMERİKA","Bridgetown",2],["Belize","KUZEY AMERİKA","Belmopan",2],["Dominika","KUZEY AMERİKA","Roseau",2],["Dominik Cumhuriyeti","KUZEY AMERİKA","Santo Domingo",3],["El Salvador","KUZEY AMERİKA","San Salvador",3],["Grenada","KUZEY AMERİKA","St. George's",2],["Guatemala","KUZEY AMERİKA","Guatemala City",3],["Haiti","KUZEY AMERİKA","Port-au-Prince",4],["Honduras","KUZEY AMERİKA","Tegucigalpa",3],["Jamaika","KUZEY AMERİKA","Kingston",3],["Kanada","KUZEY AMERİKA","Ottawa",3],["Kosta Rika","KUZEY AMERİKA","San José",3],["Küba","KUZEY AMERİKA","Havana",3],["Meksika","KUZEY AMERİKA","Mexico City",3],["Nikaragua","KUZEY AMERİKA","Managua",3],["Panama","KUZEY AMERİKA","Panama City",3],["Saint Kitts ve Nevis","KUZEY AMERİKA","Basseterre",1],["Saint Lucia","KUZEY AMERİKA","Castries",1],["Saint Vincent ve Grenadinler","KUZEY AMERİKA","Kingstown",1],["Trinidad ve Tobago","KUZEY AMERİKA","Port of Spain",3],["Bahamalar","KUZEY AMERİKA","Nassau",2],["Kuzey Kıbrıs Türk Cumhuriyeti","ASYA/AVRUPA","Lefkoşa",2],
    ["Arjantin","GÜNEY AMERİKA","Buenos Aires",4],["Bolivya","GÜNEY AMERİKA","Sucre",3],["Brezilya","GÜNEY AMERİKA","Brasília",4],["Ekvador","GÜNEY AMERİKA","Quito",3],["Guyana","GÜNEY AMERİKA","Georgetown",2],["Kolombiya","GÜNEY AMERİKA","Bogotá",3],["Paraguay","GÜNEY AMERİKA","Asunción",3],["Peru","GÜNEY AMERİKA","Lima",3],["Surinam","GÜNEY AMERİKA","Paramaribo",2],["Şili","GÜNEY AMERİKA","Santiago",3],["Uruguay","GÜNEY AMERİKA","Montevideo",3],["Venezuela","GÜNEY AMERİKA","Caracas",4],
    ["Avustralya","OKYANUSYA","Canberra",4],["Fiji","OKYANUSYA","Suva",2],["Kiribati","OKYANUSYA","South Tarawa",1],["Marshall Adaları","OKYANUSYA","Majuro",1],["Mikronezya","OKYANUSYA","Palikir",1],["Nauru","OKYANUSYA","Yaren",1],["Palau","OKYANUSYA","Ngerulmud",1],["Papua Yeni Gine","OKYANUSYA","Port Moresby",3],["Samoa","OKYANUSYA","Apia",1],["Solomon Adaları","OKYANUSYA","Honiara",2],["Tonga","OKYANUSYA","Nuku'alofa",1],["Tuvalu","OKYANUSYA","Funafuti",1],["Vanuatu","OKYANUSYA","Port Vila",2],["Yeni Zelanda","OKYANUSYA","Wellington",3]
]

var selected_country := "Türkiye"
var unlocked := {"Türkiye": true}

func countries_by_continent(continent: String) -> Array:
    return COUNTRIES.filter(func(item): return item[1] == continent)

func select_country(country: String) -> bool:
    for item in COUNTRIES:
        if item[0] == country and (unlocked.has(country) or country == "Türkiye"):
            selected_country = country
            return true
    return false

func unlock_country(country: String) -> void:
    unlocked[country] = true

func is_unlocked(country: String) -> bool:
    return unlocked.has(country)
